import { CookieConsentBanner } from "@/components/CookieConcentBanner";
import { DebugPanel } from "@/components/DebugPanel";
import { DynamicFavicon } from "@/components/DynamicFavIcon";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import { FacebookPixelProvider } from "@/components/FacebookPixelProvider";
import { ScrollToTop } from "@/components/ScrollToTop";
import { TooltipProvider } from "@/components/ui/tooltip";
import { WhatsAppIcon } from "@/components/WhatsAppIcon";
import { CartProvider } from "@/contexts/CartContext";
import { SiteSettingsProvider } from "@/contexts/SiteSettingContext";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { AuthProvider } from "./hooks/useAuth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: 1,
      staleTime: 5 * 60 * 1000,
      refetchOnWindowFocus: false,
    },
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ErrorBoundary>
      <QueryClientProvider client={queryClient}>
        <AuthProvider>
          <SiteSettingsProvider>
            <CartProvider>
              <TooltipProvider>
                <Toaster />
                {/* <Sonner /> */}
                <FacebookPixelProvider>
                  <ScrollToTop />
                  <DynamicFavicon />
                  <html
                    lang="en"
                    className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
                  >
                    <body className="min-h-full flex flex-col">{children}</body>
                  </html>
                  <CookieConsentBanner />
                  <WhatsAppIcon />
                  <DebugPanel />
                </FacebookPixelProvider>
              </TooltipProvider>
            </CartProvider>
          </SiteSettingsProvider>
        </AuthProvider>
      </QueryClientProvider>
    </ErrorBoundary>
  );
}
