import { AdminNavItem } from "@/types/admin";
import {
  CreditCard,
  FileText,
  FolderOpen,
  Image,
  LayoutDashboard,
  LayoutTemplate,
  MapPin,
  Megaphone,
  MessageSquare,
  Package,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Tag,
  Truck,
  Users,
} from "lucide-react";

export const ADMIN_NAVIGATION: AdminNavItem[] = [
  {
    name: "Dashboard",
    href: "/admin",
    icon: LayoutDashboard,
    roles: ["admin", "manager", "order_handler"],
    section: "Main",
  },
  {
    name: "Products",
    href: "/admin/products",
    icon: Package,
    roles: ["admin", "manager"],
    section: "Main",
  },
  {
    name: "Categories",
    href: "/admin/categories",
    icon: FolderOpen,
    roles: ["admin", "manager"],
    section: "Main",
  },
  {
    name: "Orders",
    href: "/admin/orders",
    icon: ShoppingCart,
    roles: ["admin", "manager", "order_handler"],
    section: "Main",
  },
  {
    name: "Checkout Leads",
    href: "/admin/checkout-leads",
    icon: Users,
    roles: ["admin", "manager"],
    section: "Main",
  },
  {
    name: "Slider",
    href: "/admin/slider",
    icon: Image,
    roles: ["admin", "manager"],
    section: "Store",
  },
  {
    name: "Coupons",
    href: "/admin/coupons",
    icon: Tag,
    roles: ["admin", "manager"],
    section: "Store",
  },
  {
    name: "Shipping Zones",
    href: "/admin/shipping",
    icon: MapPin,
    roles: ["admin"],
    section: "Store",
  },
  {
    name: "Shipping Methods",
    href: "/admin/shipping-methods",
    icon: Truck,
    roles: ["admin"],
    section: "Store",
  },
  {
    name: "Reviews",
    href: "/admin/reviews",
    icon: MessageSquare,
    roles: ["admin", "manager"],
    section: "Store",
  },
  {
    name: "Courier",
    href: "/admin/courier",
    icon: Truck,
    roles: ["admin"],
    section: "System",
  },
  {
    name: "Payment Methods",
    href: "/admin/payment-methods",
    icon: CreditCard,
    roles: ["admin"],
    section: "System",
  },
  {
    name: "Pages",
    href: "/admin/pages",
    icon: FileText,
    roles: ["admin"],
    section: "System",
  },
  {
    name: "Landing Pages",
    href: "/admin/landing-pages",
    icon: Megaphone,
    roles: ["admin"],
    section: "System",
  },
  {
    name: "Homepage",
    href: "/admin/homepage",
    icon: LayoutTemplate,
    roles: ["admin"],
    section: "System",
  },
  {
    name: "Users",
    href: "/admin/users",
    icon: ShieldCheck,
    roles: ["admin"],
    section: "System",
  },
  {
    name: "Settings",
    href: "/admin/settings",
    icon: Settings,
    roles: ["admin"],
    section: "System",
  },
];
